spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    placeholderReplacement: false
    locations:
      - classpath:db/migration

jwtSecret: "longsecurejwtsecret"
jwtExpirationMs: "86400000"